### ISSUE TITLE
Fix PARE requirement in requirement.txt 

### ISSUE THREAD

**Issue by Omri-CG** [mkocabas/SPEC#1]
Thanks for sharing this work! 
Please fix the requirement in `requirement.txt` file of [PARE](https://github.com/mkocabas/SPEC/blob/master/requirements.txt#L28). 
It should be (currently missing "git+" prefix):
`git+https://github.com/mkocabas/PARE.git`

**Comment by mkocabas** [comment]
Thanks a lot!
