### ISSUE TITLE
prepare_data.sh has inaccessible links

### ISSUE THREAD

**Issue by anticdimi** [mkocabas/SPEC#17]
Hi @mkocabas ,

Thank you for your amazing work.
 Could you please update the links with pretrained models/data for the demo? It seems like the content from dropbox was deleted, therefore, the model/data is inaccessible.

**Comment by mkocabas** [comment]
Hi @anticdimi,

Sorry I moved some data around. I have just committed a fix. Let me know if it doesn't work. Best!
