### ISSUE TITLE
Can SPEC run MAON?

### ISSUE THREAD

**Issue by zc-alexfan** [mkocabas/SPEC#2]
Dear Muhammed, a huge fan of your work. Can SPCE run MANO? 

Thank you

**Comment by mkocabas** [comment]
Hi Alex,

Thanks a lot for your interest in our work :) In its current state, unfortunately no. Even though SPEC can be extended to hands, the need for this is questionable. In full body, overall pose, shape and global orientation, which should be modeled accurately for different application scenarios, is affected by our weak perspective assumptions. And, here we show that perspective camera estimated from a single image is better than weak perspective cam. One needs to figure out whether such benefits from modelling a perspective camera would help hand pose and shape.
