### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by Dene33** [mkocabas/SPEC#6]
Is there a way to get all the camera params? Translation in the world for instance. Or even to get just R, T, K matrices? Thanks

**Comment by mkocabas** [comment]
Yes, there is. You can obtain R and K from CamCalib predictions using this function: 

https://github.com/mkocabas/SPEC/blob/master/spec/utils/cam_params.py#L24-L50

**Comment by ZhiguoZhao** [comment]
Thanks ,I wand to know how to find T
